version: '3.7'

networks:
  design:

volumes:
  mongo-data:
  minio-data-new:

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
#    volumes:
#        - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always
    networks:
      - design
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
    - ./api:/usr/src/api
    ports:
      - 8080:8000
    restart: always
    networks:
      - design
    environment:
      - "MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F"
      - "MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"

  minio:
    image: minio/minio:RELEASE.2020-06-14T18-32-17Z
    command: server /design
    volumes:
      - minio-data-new:/design
    networks:
      - design
    ports:
      - 9000:9000
    environment:
      - "MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F"
      - "MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"

  mongo:
    image: mongo
    volumes:
      - "mongo-data:/data/db:rw"
    ports:
      - 27017:27017
    networks:
      - design
